
name: Update README with Recent Activity

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every hour; adjust the frequency as needed
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with Recent Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README
        uses: actions-cool/issues-helper@v1
        with:
          owner: emurmudu
          repo: emurmudu
          token: ${{ secrets.GH_TOKEN }}
