name: update-readme
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: emurmudu/update-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
